### ISSUE TITLE
Add box plot feature for data integrity/edge case detection

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#100]
We currently support only custom-defined metrics for [edge cases](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/edge_case.py) and [data integrity](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/data_integrity.py). 

Add [boxplots](https://www.geeksforgeeks.org/box-plot-in-python-using-matplotlib/) and Tukey's fences for edge case checks in the UpTrain frameworks to identify outliers in data.

**Comment by Abhiramkns** [comment]
Hi @vipgupta, I would like to work on this.

**Comment by vipgupta** [comment]
Solved.
