### ISSUE TITLE
Add Z-score analysis for data integrity

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#101]
We currently support only custom-defined metrics for [edge cases](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/edge_case.py) and [data integrity](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/data_integrity.py).

Add [Z-score analysis](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html) in UpTrain to identify outliers in the data.

**Comment by lokeshwarlakhi** [comment]
Hey @vipgupta , can you assign this issue to me. I can do this.

**Comment by vipgupta** [comment]
Done! Let's chat in the Discord community group if you have any questions :)

**Comment by lokeshwarlakhi** [comment]
Sure thing! 👍🏾

**Comment by Dominastorm** [comment]
Solved by #212
