### ISSUE TITLE
🌎 Translate the UpTrain Readme to German

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#104]
A translation for README.md in German would allow developers who prefer reading in German to understand what UpTrain is about quickly.

**Comment by tuhinmallick** [comment]
I can help out with this issue. Is it available?

**Comment by vipgupta** [comment]
Hey @tuhinmallick, that would be very helpful. If needed, you can use this [link](https://github.com/dephraiim/translate-readme) as a starting point.

**Comment by vipgupta** [comment]
@tuhinmallick Can you proofread the readme in German here: https://github.com/uptrain-ai/uptrain/blob/main/i18n/README.de.md

We have removed the yml workflow because it got triggered with every commit (and had obvious translation errors).

**Comment by Dominastorm** [comment]
This was solved by #157
