### ISSUE TITLE
🌎 Translate the UpTrain Readme to Spanish

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#106]
Spanish is widely spoken in many countries, including Spain, Mexico, and South America. Many software developers and companies in these regions use Spanish as their primary language for development. It would be great to have a version of README.md in Spanish for these developers to get started with UpTrain quickly.

**Comment by scorcism** [comment]
Hey, for this can we use directly `https://github.com/dephraiim/translate-readme`

**Comment by vipgupta** [comment]
Thanks for sharing the link. I think it can be used as a good starting point, but it would be nice to get it verified by a native speaker.

**Comment by scorcism** [comment]
yes, but for inital use we can take this into consideration until someone native to that language contributes.

**Comment by vipgupta** [comment]
Solved by https://github.com/uptrain-ai/uptrain/pull/157
