### ISSUE TITLE
Add a Reinforcement Learning Example

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#107]
Add an ML model monitoring example in the Reinforcement Learning domain.

**Comment by a-r-r-o-w** [comment]
I'm interested in contributing to this issue. Can this be assigned to me? Also, I would like to confirm if there are any specific RL examples you want me to focus on.

I was planning on creating an example that utilizes the [OpenAI Gym](https://gymnasium.farama.org/). What are your thoughts on this?

**Comment by vipgupta** [comment]
Hi @a-r-r-o-w, issue assigned :) The example does not have to be a specific RL problem, but should have a good business use case in general. OpenAI Gym sounds good.
