### ISSUE TITLE
Add more examples on model bias

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#108]
Currently, we have only one measure of [recommendation bias](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/recommendation_bias.py) in the repository: [Popularity Bias](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/algorithms/popularity_bias.py).

It would be great to have many other measures of bias implemented in the repository, such as exposure bias, position bias, bias towards any particular feature (such as race and gender), etc. 

You can check out this [blog](https://uptrain.ai/blog/bias-in-recommendation-systems) to learn more about biases in recommendation models.

**Comment by bhoomeendra** [comment]
@vipgupta  The Blog link doest not exits

**Comment by Dominastorm** [comment]
> @vipgupta  The Blog link doest not exits

https://uptrain.ai/blog/model-bias-in-recommendation-systems
