### ISSUE TITLE
Change class name from "Anomaly" to "Monitor"

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#109]
"Monitor" is a better name for the [Anomaly](https://github.com/uptrain-ai/uptrain/tree/main/uptrain/core/classes/anomalies) classes currently defined in the UpTrain framework. We want to replace the words Anomaly (Anomalies) with Monitor (Monitors), respectively.

This is a good first issue for users to get acquainted with the UpTrain framework.

**Comment by lklivingstone** [comment]
Hello, I am interested in this issue. Can I be assigned?

**Comment by vipgupta** [comment]
@lklivingstone definitely, would love to have you contribute. However, I would recommend checking out PR #112 (and my comment there) before you get started.

**Comment by vipgupta** [comment]
Solved by #129
