### ISSUE TITLE
Change variable name from "Recommendation Bias" to "Model Bias"

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#110]
Recommendation bias implies that bias monitoring happens only for recommender systems. However, bias can be present in any model that makes predictions (for example, a model shortlisting applicants but prefers CVs of white males, implying racism and gender bias).

We want to change all mentions of recommendation bias, starting with [this file](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/recommendation_bias.py), to model bias.

This is also a good first issue to get started with UpTrain.

**Comment by kushalnl7** [comment]
Hi, I am interested in this. Can I work on this?

**Comment by vipgupta** [comment]
Hi @kushalnl7, definitely! Assigned the issue :)

**Comment by vipgupta** [comment]
@kushalnl7 Let me know if you are working on this issue/

**Comment by kushalnl7** [comment]
Yes, I am doing it.

**Comment by vipgupta** [comment]
Solved by MR #121 by @kushalnl7
