### ISSUE TITLE
Move logging-related args under logging args

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#115]
In [config_handler.py](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/helpers/config_handler.py), remove logging-related arguments like `st_logging` and `log_data` to the class `LoggingArgs`.

This is a good first issue to get started with UpTrain.

**Comment by scorcism** [comment]
Hello there, can I work on this ?

**Comment by vipgupta** [comment]
Yes, please :) Thanks for your interest.

**Comment by scorcism** [comment]
I just have to move the two varibales into LoggingArgs class ? m i correct

**Comment by vipgupta** [comment]
Yes, but then you also need to make sure that wherever these two variables are called in the repo, they are now referred properly (search in VS code comes very handy here). For example, [this line](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/framework.py#L65) would become 
`self.log_data = cfg.logging_args.log_data
`

**Comment by scorcism** [comment]
okay thank you, will starting working on it

**Comment by scorcism** [comment]
Varibles changed in : https://imgur.com/kVaNJBj.png file
**Changes**

- In `framework.py` : https://imgur.com/AADEWek.png
- In `config_handler.py` : https://imgur.com/PbawYmX.png
- In `log_handler.py` : https://imgur.com/7Posn4J.png

**Comment by vipgupta** [comment]
Hi @scorcism , these look good. Feel free to submit your PR, and we can update it incrementally. It doesn't have to be perfect in the first draft.

Other than that, I also think many examples are referring `st_logging`. That now has to be brought into the dictionary `logging_args`. Eg, block 7 [fraud detection example](https://github.com/uptrain-ai/uptrain/blob/main/examples/fraud_detection/run.ipynb) currently looks like this
```python
cfg = {
    # Checks to identify concept drift
    "checks": [{
        'type': uptrain.Anomaly.CONCEPT_DRIFT,
        'algorithm': uptrain.DataDriftAlgo.DDM
    }],
    
    # Folder that stores the drifted data-points identified by UpTrain
    "retraining_folder": 'uptrain_smart_data',
    
    # Enable streamlit logging to visualize model's performance
    "st_logging": True,
}
```

But after your change, it will become
```python
cfg = {
    # Checks to identify concept drift
    "checks": [{
        'type': uptrain.Anomaly.CONCEPT_DRIFT,
        'algorithm': uptrain.DataDriftAlgo.DDM
    }],
    
    # Folder that stores the drifted data-points identified by UpTrain
    "retraining_folder": 'uptrain_smart_data',
    
    # Enable streamlit logging to visualize model's performance
    "logging_args": {"st_logging": True},
}
```

**Comment by scorcism** [comment]
okay, so I need to chnage this all or make a PR ?

**Comment by vipgupta** [comment]
You can start by making a PR, and then we can discuss it (we can always push more commits to a PR).

**Comment by scorcism** [comment]
okay maing a PR
