### ISSUE TITLE
Make UMAP package requirement optional with UpTrain package

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#128]
Currently, UpTrain requires users to install UMAP concurrently (e.g., see [this](https://github.com/uptrain-ai/uptrain/blob/main/setup.py#L48)).

However, this is not needed until some user adds a UMAP visualization requirement in the config (for example, we have such visualization requirement in the [text summarization example](https://github.com/uptrain-ai/uptrain/blob/main/examples/text_summarization/run.ipynb)).

**Issue**: We want to remove the UMAP installation requirement from UpTrain by prompting users to install UMAP independently if they have defined a UMAP check in the config.

One way to do that is "try" importing the UMAP package in this [if condition](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/managers/check_manager.py#L90), if it doesn't work, then print something like "UMAP installation not found. For UMAP visualization, please install with `pip install umap-learn`."

This is a good first issue to get started with UpTrain.

**Comment by dineshladi** [comment]
@vipgupta I will be working on this issue.

**Comment by vipgupta** [comment]
Sounds good. @dineshladi

**Comment by dineshladi** [comment]
@vipgupta, I have started working on the solution. The issue seems a little more complicated than expected. try-except wrapped inside conditional checks of config type won't alone solve the issue. The umap package is imported as part of this visual module as well https://github.com/uptrain-ai/uptrain/blob/41ffa2170b321cbd76fd9c4d7117e3992dfa9023/uptrain/core/classes/visuals/umap.py#L1.  Any suggestions how we can solve this?

**Comment by vipgupta** [comment]
Can we also add `try/except` statement here? At the end of the day, if we are not passing UMAP check in the check_manager [here](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/managers/check_manager.py#L90), UMAP won't be needed.

**Comment by dineshladi** [comment]
sure. let me try that

**Comment by dineshladi** [comment]
@vipgupta, the issue still would be there even if we are not passing UMAP check in check manager. We would get no module found errors even if we don't any umap related checks. See the below traceback while importing uptrain after removing umap as dependency and adding try-except in framework and umap visual module. 

```
>>> import uptrain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ladidinesh/Documents_Local/oss/dineshladi/uptrain/uptrain/__init__.py", line 1, in <module>
    from uptrain.core.classes import Framework
  File "/Users/ladidinesh/Documents_Local/oss/dineshladi/uptrain/uptrain/core/classes/__init__.py", line 1, in <module>
    from .framework import Framework
  File "/Users/ladidinesh/Documents_Local/oss/dineshladi/uptrain/uptrain/core/classes/framework.py", line 17, in <module>
    from uptrain.core.classes.managers import CheckManager
  File "/Users/ladidinesh/Documents_Local/oss/dineshladi/uptrain/uptrain/core/classes/managers/__init__.py", line 1, in <module>
    from .check_manager import CheckManager
  File "/Users/ladidinesh/Documents_Local/oss/dineshladi/uptrain/uptrain/core/classes/managers/check_manager.py", line 19, in <module>
    from uptrain.core.classes.visuals import Umap, Tsne, Shap
  File "/Users/ladidinesh/Documents_Local/oss/dineshladi/uptrain/uptrain/core/classes/visuals/__init__.py", line 2, in <module>
    from .umap import Umap
  File "/Users/ladidinesh/Documents_Local/oss/dineshladi/uptrain/uptrain/core/classes/visuals/umap.py", line 7, in <module>
    import umap
ModuleNotFoundError: No module named 'umap'
```

**Comment by vipgupta** [comment]
@dineshladi Did you have any questions? I meant earlier that we could have the following try/except in umap.py

```
try:
  import umap
except:
  pass
```
I think this should work. Let me know.

**Comment by dineshladi** [comment]
hi @vipgupta, i have tried this and it doesn't completely solve the issue. Is there any other place where we can have a discussion (maybe a discord server)?

**Comment by vipgupta** [comment]
Hi @dineshladi , yes! Please hop on to the server here: https://discord.com/invite/gVvZhhrQaQ

I am vipgupta
