### ISSUE TITLE
Change name AbstractAnomaly to AbstractMonitor

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#132]
As a better naming convention, we want to change the name of files (and classes inside) from [abstract_anomaly.py](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/monitors/abstract_anomaly.py) and [custom_anomaly.py](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/monitors/custom_anomaly.py) to `abstract_monitor.py` and `custom_monitor.py`, respectively. Note that the class names inside also need to be changed (that is, change `AbstractAnomaly` to `AbstractMonitor`). 

A good first issue to get started with UpTrain.

**Comment by emergenitro** [comment]
Hello! May I take this up?

**Comment by vipgupta** [comment]
Solved by #133
