### ISSUE TITLE
Add a concept drift algorithm for regression tasks

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#135]
Concept drift is the measure of model performance degradation. For binary classification, we use the [DDM algorithm](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/algorithms/data_drift_ddm.py). We want to implement a concept drift detection algorithm for regression tasks as well.

The concept drift algorithm will go inside [this if-else condition](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/monitors/concept_drift.py#L23) in `concept_drift.py`.

[ADWIN](https://riverml.xyz/dev/api/drift/ADWIN/) is a good algorithm to get started (but feel free to implement your own).

**Comment by parthpankajtiwary** [comment]
Hi @vipgupta,

Is this issue still relevant? I see you have sourced in the drift algorithms from `river` in the codebase.

**Comment by vipgupta** [comment]
Hi @parthpankajtiwary! Yes, this is solved. Thanks for pointing this out :)
