### ISSUE TITLE
Inherit UMAP and TSNE from a common class

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#143]
UMAP and TSNE have very similar codes. Combine and inherit from a single class to avoid code duplication

**Comment by vipgupta** [comment]
@Dominastorm this is related to the bug you mentioned in Issue #144. The code for UMAP and t-SNE is 90% same. You can try solving this issue to get started (also, happy to discuss whenever).

**Comment by Dominastorm** [comment]
Sure thing, I will start working on it!

**Comment by vipgupta** [comment]
Solved by #179
