### ISSUE TITLE
Code discrepancy

### ISSUE THREAD

**Issue by Dominastorm** [uptrain-ai/uptrain#150]
While comparing the code between TSNE and UMAP, I noticed that there was a discrepancy in two lines.

The following lines in TSNE are not filtering any values
https://github.com/uptrain-ai/uptrain/blob/2eeffe709fd9afc3d8538df2074d209954bf2dea/uptrain/core/classes/visuals/tsne.py#L175
https://github.com/uptrain-ai/uptrain/blob/2eeffe709fd9afc3d8538df2074d209954bf2dea/uptrain/core/classes/visuals/tsne.py#L182

The same lines in UMAP are filtering to check if the substring is present in the values
https://github.com/uptrain-ai/uptrain/blob/2eeffe709fd9afc3d8538df2074d209954bf2dea/uptrain/core/classes/visuals/umap.py#L155
https://github.com/uptrain-ai/uptrain/blob/2eeffe709fd9afc3d8538df2074d209954bf2dea/uptrain/core/classes/visuals/umap.py#L162

What is the desired behaviour here?

**Comment by vipgupta** [comment]
Solved by #179
