### ISSUE TITLE
Set hover text default as data-point ID in umap

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#158]
Currently, the user needs to mention the text they want to show in UMAP hover explicitly. However, we want id to be default hover (plus add whatever the user provided in `hover_args`). See [text summarization example](https://github.com/uptrain-ai/uptrain/blob/main/examples/text_summarization/run.ipynb) for details.

**Comment by sanjaybora04** [comment]
hi @vipgupta 
I would like to work on this issue

**Comment by vipgupta** [comment]
Hi @sanjaybora04, thanks for your interest. Please go ahead and try it out. Let me know if you run into any issues.

**Comment by sanjaybora04** [comment]
@vipgupta I am trying to understand the codebase so it will take some time

**Comment by sanjaybora04** [comment]
@vipgupta is umap visualization only available for training language models?

**Comment by Dominastorm** [comment]
Hey @sanjaybora04, UMAP is not limited to language models. It is used to reduce the dimensionality of data for visualization. Since, we cannot visualize data in higher dimensions like 5D on our computers, we use UMAP to reduce it to a lower dimension like 2 or 3. 

It takes a numerical array of higher dimension as input and returns an array of lower dimension as output (2 in our case). This array can belong to any kind of model.

Here's a great video if you wish to learn more about it: https://youtu.be/eN0wFzBA4Sc

**Comment by vipgupta** [comment]
@Dominastorm is correct. Any group of high-dimensional vectors can be visualized through UMAP. However, we can also show text for language models in hover args. That's why we want to also add data-point `id` in hover args by default so that the user can relate the data-point to the high-dimensional vector (which can be an image, for example).

**Comment by sanjaybora04** [comment]
@vipgupta  
![Screenshot from 2023-03-19 22-18-47](https://user-images.githubusercontent.com/109687297/226191742-10e407bd-cbe3-4e8a-a8c6-41b36d8b0562.png)

Is this good?
it shows the `index` at the top
you meant `index` by `id` right?

**Comment by sanjaybora04** [comment]
![Screenshot from 2023-03-19 22-42-40](https://user-images.githubusercontent.com/109687297/226194542-e8c24f5d-9e51-4713-9e6c-defae5dfdd38.png)

**Comment by vipgupta** [comment]
This is great. Can you submit a PR?

**Comment by sanjaybora04** [comment]
> This is great. Can you submit a PR?

@vipgupta i've submitted a PR

**Comment by Dominastorm** [comment]
> > This is great. Can you submit a PR?
> 
> @vipgupta i've submitted a PR

Can you check again? I don't see a Pull Request from you.

**Comment by sanjaybora04** [comment]
@Dominastorm https://github.com/uptrain-ai/uptrain/pull/171
It was merged but @vipgupta found another way to do it so he is working on it now
