### ISSUE TITLE
Add API reference guide 

### ISSUE THREAD

**Issue by TueLindhart** [uptrain-ai/uptrain#165]
**Is your feature request related to a problem? Please describe.**
I find the documentation lagging in information and find it hard to determine if UpTrain is something we can use. A API reference would be nice to understand the functionality of the different functions. 

**Describe the solution you'd like**
API reference, 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vipgupta** [comment]
Hi @TueLindhart, please check out the [How to use UpTrain](https://docs.uptrain.ai/docs/how-to-use-uptrain) section of the documentation. It discusses defining the config and logging data to the UpTrain framework, which is all you need to get started. We have some comprehensive examples you can look at to understand how to use UpTrain. 

That being said, the documentation is a work in progress. Please tell me about your use-case so we can focus on adding appropriate parts to the documentation.

**Comment by Dominastorm** [comment]
Solved by #287
