### ISSUE TITLE
Dimensionality Reduction with PCA

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#225]
Currently, we have UMAP and t-SNE [dimensionality reduction](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/visuals/dimensionality_reduction.py). We also want to add PCA where the PCA vectors are calculated w.r.t the reference dataset and during testing, the 2D/3D projections are obtained w.r.t these PCA vectors.

**Comment by Abhiramkns** [comment]
Hello @vipgupta, can I work on this issue?

**Comment by vipgupta** [comment]
Hi @Abhiramkns Please go ahead :)

**Comment by vipgupta** [comment]
Hi @Abhiramkns, this is not the input data. This is a reference dataset (which is generally the training data). We first obtain the PCA vectors using the training data and then project the test points on that vector space.

**Comment by Abhiramkns** [comment]
I create a PR for this #272 . Could you please take a look at it when free?
