### ISSUE TITLE
Add example for a LLM model

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#34]
- Create an example to highlight how UpTrain can be used to smartly fine-tune a LLM
- Define a model signal using sentiment analysis
- Define a model signal using keyword search

**Comment by vipgupta** [comment]
Assigning this to [a-r-r-o-w](https://github.com/a-r-r-o-w)

**Comment by vipgupta** [comment]
Solved by #89 by @a-r-r-o-w
