### ISSUE TITLE
Add more recommendation biases

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#35]
More info here - https://uptrain.ai/blog/bias-in-recommendation-systems

**Comment by Rajarshi-1998** [comment]
I would like to contribute to this issue.

**Comment by vipgupta** [comment]
Hi @Rajarshi-1998, same for this issue! Would be more than happy to have you contribute. Please take a look at [contributing instructions](https://github.com/uptrain-ai/uptrain/blob/main/CONTRIBUTING.md) to get started.

**Comment by sourabhagr** [comment]
@Rajarshi-1998 - maybe you can start with defining a metric to quantify and track position bias? 

(An user is more likely to click on top recommended video even if it doesn't align 100% with their preferences). I got a cool paper which discusses this bias - "learning to rank with selection bias in personal search"
