### ISSUE TITLE
Add example for a Computer vision based use-case

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#38]

**Comment by Rajarshi-1998** [comment]
I would like to contribute to this issue.

**Comment by vipgupta** [comment]
Hi @Rajarshi-1998, would love for you to contribute. Please take a look at the [contributing instructions](https://github.com/uptrain-ai/uptrain/blob/main/CONTRIBUTING.md) to get started. In the meantime, I would be happy to answer any questions.

**Comment by Abhay06102003** [comment]
Want to Contribute 
Please send me some instructions to complete the contribution 
Thanks

**Comment by vipgupta** [comment]
Hi @Abhay06102003, the detailed instructions can be found at [contributing instructions](https://github.com/uptrain-ai/uptrain/blob/main/CONTRIBUTING.md). Also, we can chat on the [community Discord](https://discord.com/invite/gVvZhhrQaQ) to further nail down your contribution.

**Comment by sourabhagr** [comment]
Thanks @vipgupta! 

@Abhay06102003 - maybe you can try adding an example where we measure data drift in image brightness? You can take a simple image classification task with publicly available models. Do check out the "1_orientation_classification" example.

**Comment by Abhay06102003** [comment]
Thanks for your recommendation @sourabhagr

**Comment by Abhay06102003** [comment]
Please assign me this issue!
I am almost finishing my work.

**Comment by vipgupta** [comment]
Done! Looking forward to reading your MR.

**Comment by Abhay06102003** [comment]
I am making a good example of use case CV model names Object Detection of about 80 classes.
