### ISSUE TITLE
Private / Azure OpenAI endpoints

### ISSUE THREAD

**Issue by nielsuit227** [uptrain-ai/uptrain#440]
**Is your feature request related to a problem? Please describe.**
I cannot use this now as I'm restricted to an Azure OpenAI endpoint, and EvalLLM only takes an api key.

**Describe the solution you'd like**
I should be able to define my endpoint, similar to the OpenAI python sdk. 

**Describe alternatives you've considered**
promptfoo, prompttools, etc...

**Additional context**

**Comment by sourabhagr** [comment]
@nielsuit227, thanks for raising this request. We allow Azure endpoints in the managed version (i.e. the one that uses the UpTrain API key). You can create a free account here: https://uptrain.ai/. You can specify the model, Azure API keys, and endpoints in the settings object for the same. 

@ashish-1600, can we add a tutorial for the same?

**Comment by ashish-1600** [comment]
Sure @sourabhagr . I will add a tutorial for this.

**Comment by lalehsg** [comment]
Hi all! I have a related question. Wanted to confirm list of LLM providers (judges) that are supported by the platform. I see GPT3.5, GPT4, Claude and Cohere [in the documentation](https://github.com/uptrain-ai/uptrain?tab=readme-ov-file#integrations). Based on this issue, seems that Azure open ai is also supported. Was wondering if any other LLM (open source and/or self-hosted endpoints) are supported as well? Thanks in advance!

**Comment by sourabhagr** [comment]
Hi @nielsuit227 and @lalehsg, we are working on this and will make this change in the next few weeks. On the open-source front, how are you hosting those LLMs? Are these self-hosted endpoints (called via REST APIs?) or are you using providers like TogetherAI/AnyScale/HuggingFace?  We can prioritise the development accordingly

**Comment by ashish-1600** [comment]
Hey @nielsuit227 , We have enabled Azure OpenAI endpoint for EvalLLM as well. Please have a look at this tutorial. [Open-source EvalLLM Evaluator](https://github.com/uptrain-ai/uptrain/blob/main/examples/open_source_evaluator_tutorial.ipynb)
