### ISSUE TITLE
Create a tutorial for ROUGE score

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#487]
**Is your feature request related to a problem? Please describe.**
Currently we don't have any tutorial to show how to use ROUGE score (https://github.com/uptrain-ai/uptrain/blob/main/uptrain/operators/language/rouge.py)

**Describe the solution you'd like**
Add a tutorial on how to use ROUGE operator.

**Comment by Dominastorm** [comment]
Done in #507
