### ISSUE TITLE
Support CLASSIFY eval type for Response Consistency eval

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#528]
Currently, the response consistency eval prompt only supports Chain-of-thought prompting as it asks for an explanation for the score. Support the case where explanation is not needed.

Relevant code snippets:
"uptrain/operators/language/prompts/classic.py"
and evaluate_local at ResponseConsistency Operator at "uptrain/operators/language/response_quality.py"

**Comment by Abhiramkns** [comment]
Hello @sourabhagr , Can I work on this issue?

**Comment by sourabhagr** [comment]
Hey @Abhiramkns, yeah sure! For some reference, look at the ResponseCompleteness Eval, https://github.com/uptrain-ai/uptrain/blob/a061b293e5c62edea40ea563467348cf62ad1cfe/uptrain/operators/language/response_quality.py#L132

It has two modes:  basic and cot with different prompts, few shot examples, etc.

We want the do the same for ResponseConsistency Eval:

Basic - Generate a reasoning on why the given response is an appropriate answer for the given question, and then ask LLM to score the logical correctness of the reasoning

COT - Generate a reasoning on why the given response is an appropriate answer for the given question, and then ask LLM to score the logical correctness of the reasoning along with the reasoning

Feel free to let me know if you face any issues

**Comment by Abhiramkns** [comment]
<img width="1345" alt="Screenshot 2024-02-21 at 1 33 10 AM" src="https://github.com/uptrain-ai/uptrain/assets/55329359/5a5a9938-1b29-4b16-9102-21b1c0666b74">
@sourabhagr I was testing with an example in basic eval type for Response consistency and Response completeness to understand the difference. For response consistency, it is not returning reasoning for logical correctness score. 

I'm confused about what to do. Can you share with me an example?

**Comment by sourabhagr** [comment]
Hi @Abhiramkns, yes, I am working on an example to explain the above. Will share by tomorrow

**Comment by sourabhagr** [comment]
Hi @Abhiramkns, so I believe you need to make following changes:

1. Modify the prompt of Response consistency to incorporate {prompting instructions}. If you look at line 2 of the prompt, 

"For the provided task data, come up with an argument to justify why the given answer is appropriate for the given question. Finally give a score between 0 to 1, indicating how logical the argument looks like along with an explanation for the score."

Instead of always asking for explanation, we can ask it only in case of cot. Something like this might work:
"For the provided task data, come up with an argument to justify why the given answer is appropriate for the given question. Finally, give a score between 0 to 1, indicating how logical the argument is. {prompting_instructions}"

Code at https://github.com/uptrain-ai/uptrain/blob/8b74debac098154ebfc371d148d729d439e4cd6b/uptrain/operators/language/prompts/classic.py#L148

2. The output format for response consistency should also return the "argument to justify why the given answer is appropriate for the given question." Code at https://github.com/uptrain-ai/uptrain/blob/8b74debac098154ebfc371d148d729d439e4cd6b/uptrain/operators/language/prompts/output_format.py#L104

In case of classify:  we return "argument" and "score".. In case of cot: we return "argument", "reasoning", "score".

3. Make changes to the few shot examples. I believe the current few shot examples are not correct. The example data should have "question", "context", "response".  Probably create three cases where scores should be 0, 0.5, 1.  The LLM response is not consistent when the model is confused on what to answer, so you can create clever cases where the context has conflicting information. The output should be argument & score (for classify) and argument, reasoning, & score (for cot). Code here: https://github.com/uptrain-ai/uptrain/blob/8b74debac098154ebfc371d148d729d439e4cd6b/uptrain/operators/language/prompts/few_shots.py#L162

4. Make changes to ResponseConsistency Operator: 
a. score_mapping is not required as we are directly asking for a score
b. similar changes in validation functions
c. Explanation should be Argument followed by reasoning in case of cot.
Code here: https://github.com/uptrain-ai/uptrain/blob/8b74debac098154ebfc371d148d729d439e4cd6b/uptrain/operators/language/response_quality.py#L343

Let me know, we can hop on a quick call to discuss these

**Comment by Abhiramkns** [comment]
Hey @sourabhagr, can you take a look at this (PR)[https://github.com/uptrain-ai/uptrain/pull/583] when you are free? Let me know if any changes are required.

**Comment by ashish-1600** [comment]
Hey @Abhiramkns ,
I have resolved the conflicts. The PR has been merged. :)

**Comment by Abhiramkns** [comment]
Thank you so much @ashish-1600 @sourabhagr !!
