### ISSUE TITLE
Fresh venv install following the Quickstart example fails due to ModuleNotFoundError: No module named 'fsspec'

### ISSUE THREAD

**Issue by cfrenchi** [uptrain-ai/uptrain#599]
**Describe the bug**
I created a new venv environment to test out the [Quickstart](https://docs.uptrain.ai/getting-started/quickstart) example. With a new notebook and after a `pip install uptrain`, when importing in the EvalLLM and Evals I get the error ModuleNotFoundError: No module named 'fsspec'

**To Reproduce**

1. Fresh install of python
2. `python -m venv venv`
3. `source venv/bin/activate`
4. Create a new .ipynb
5. `pip install uptrain`
6. Successful pip install
7. Create a new cell with only 
`from uptrain import EvalLLM, Evals 
import json`
8. The cell will fail for ModuleNotFoundError: No module named 'fsspec'

`pip install fsspec` fixes the problem but should either be included in the package or called out in documentation

**Expected behavior**
When following the example from the Quickstart all dependencies should be installed (either through the package or by calling it out explicitly in the documentation.

**Screenshots**
<img width="1024" alt="image" src="https://github.com/uptrain-ai/uptrain/assets/10055468/2784fd58-ff9e-4504-8867-1d64ca895ab3">
![image](https://github.com/uptrain-ai/uptrain/assets/10055468/4fcad511-6699-4787-afcc-a352e345428e)

**Additional context**
To get around this I just needed to do a `pip install fsspec`
If this is a requirement it should be included in the package or called out as a dependency in documentation

**System Environment**
Sonoma 14.3.1
Python 3.11.7
VSCode 1.86.2 (Universal)
  Jupyter Extension - v2024.1.1

**Comment by Dominastorm** [comment]
Thanks for bringing this to our attention, @cfrenchi! Fixed this in #603
