### ISSUE TITLE
FastAPI deployment

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [uptrain-ai/uptrain#654]
I am trying to deploy only three metrics (FACTUAL_ACCURACY, CONTEXT_RELEVANCE, RESPONSE_RELEVANCE). And this is the code that I am using to make an endpoint for `Factual_accuracy`:

```
class EvaluationResponse(BaseModel):
    result: dict
    error: Optional[str] = None

@app.get("/")
async def read_root():
    return {"message": "Welcome to the LLM Evaluation API"}

@app.post("/evaluate/hallucination", response_model=EvaluationResponse)
async def hallucination_detect(id: str):
    try:
        data = [
            {
                "question": "Hello",
                "context": "Hello",
                "response": "Hello",
            }
        ]
        result = await eval_llm.evaluate(
            data=data,
            checks=[Evals.FACTUAL_ACCURACY],
        )
        return EvaluationResponse(result=result)
    except Exception as e:
        return EvaluationResponse(result={}, error=str(e))
```

Now, the problem is that as _hallucination_detect_ method is async and there is already a running loop in `llm.py` and in `llm.py`, `"Detected a running event loop, scheduling requests in a separate thread."` the already running loop is being used to make the async call but everytime, I run the code and use swagger UI of FastAPI to run the function, it does nothing and it got stopped on the tqdm with no output. I even made the `evaluate` method async but it's not working at all.

**Comment by ashish-1600** [comment]
Hi @HasnainKhanNiazi ,
Thanks for raising this issue. 

I have figured out a way to get this working in your use-case. 
I am using uvicorn as my ASGI web server framework. In uvicorn, we have to set the event loop as 'asyncio'.

I am attaching the code for your reference.
```python 
@app.get("/")
async def read_root():
    return {"message": "Welcome to the LLM Evaluation API"}

@app.post("/evaluate/hallucination", response_model=EvaluationResponse)
async def hallucination_detect():
    try:
        data = [
            {
                "question": "Hello",
                "context": "Hello",
                "response": "Hello",
            }
        ]
        result = eval_llm.evaluate(
            data=data,
            checks=[Evals.FACTUAL_ACCURACY],
        )
        print(result)
        return EvaluationResponse(result=result)
    except Exception as e:
        return EvaluationResponse(result={}, error=str(e))
    

if __name__ == "__main__":
    uvicorn.run("app:app", host="0.0.0.0", port=4300, loop='asyncio')

```
You don't have to make any changes in the EvalLLM. Let me know if it works for you. :)

**Comment by HasnainKhanNiazi** [comment]
@ashish-1600 Thanks, that was the issue indeed.
