### ISSUE TITLE
docker image to multi architecture

### ISSUE THREAD

**Issue by DrinkingMilktea** [uptrain-ai/uptrain#691]
I'm try to use uptrain in M3 macbook laptop. But
```
bash run_uptrain.sh
```
it gave me following error message.
```
server-1     | exec /usr/local/bin/python: exec format error
```

I searched it and find out that it is architecture problem.
I'm trying to use QEMU to emulating x86 architecture in my M3(arm) laptop.
But it's very difficult to use it.
Please Make image to multi architecture.

------------------

I found that uptrain/dashboard folder has DockerFile which can build image myself.
but I have a suggestion that DockerFile to Dockerfile which can detact docker to Dockerfile

------------------

I hope to commit about this problem. but there is no permission to me. so I can't push my commit to repo (sad)

-------------------

I read the contribution docs and make [PR](https://github.com/uptrain-ai/uptrain/pull/692)

**Comment by ashish-1600** [comment]
Hey @DrinkingMilktea ,
We've tested the images on both M1 and M2, and they're working perfectly. Additionally, I've reviewed the PR and it looks good to me.

**Comment by ashish-1600** [comment]
I have merged the PR. :)
