### ISSUE TITLE
Replace csv by SQLite in UpTrain framework

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#74]

**Comment by kanhaiyanathani** [comment]
Hi @sourabhagr @vipgupta , 
can you please point me to the right file/files where we are loading csv files, OR any documentation for the same?

**Comment by vipgupta** [comment]
Hi @kanhaiyanathani, thanks for your interest in this issue, but @ananis25 is actively working on this issue. Any other issues you find interesting?
