### ISSUE TITLE
Add option for Incremental update for histograms

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#76]

**Comment by lokeshwarlakhi** [comment]
Hey @vipgupta, can you elaborate more on what do you mean by “incremental update” here?

**Comment by vipgupta** [comment]
Hi @lokeshwarlakhi, thanks for your interest. This issue will actually be resolved in the next MR. Can I recommend issue #86 ?

**Comment by vipgupta** [comment]
Solved by MR #92
