### ISSUE TITLE
Config should be pydantic classes, not dictionaries

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#82]

**Comment by ptaban** [comment]
Hey, u can assign me this one, so i can go a little bit over repo, then i can do monitoring..
Thanks!

**Comment by vipgupta** [comment]
Hey @ptaban, Sure!

**Comment by ptaban** [comment]
Is there specific place for config? What do u mean by config?  Can u give me more context?

**Comment by vipgupta** [comment]
Hi @ptaban, config is a dictionary where you define metrics to monitor, such as data drift, edge cases, recommendation biases, etc. You can take a look at the UpTrain documentation here to get a better idea: https://docs.uptrain.ai/docs/how-to-use-uptrain

**Comment by vipgupta** [comment]
@ptaban Also, I should warn you that this is not an ideal first issue to solve. Might require diving deep into the code.
