### ISSUE TITLE
Add an illustration of multi-thread communication (for streamlit)

### ISSUE THREAD

**Issue by vipgupta** [uptrain-ai/uptrain#86]
Checkout out the file: https://github.com/uptrain-ai/uptrain/blob/main/uptrain/tests/test_dashboard.py

Here, streamlit dashboard runs in a separate thread and plots data that is logged in the folder `uptrain_logs`. Can we make the main thread and the streamlit thread communicate? This article might help: https://www.geeksforgeeks.org/python-communicating-between-threads-set-1/

The task is to create an illustration of the threads communicating. For example, we input something from the streamlit dashboard and it prints at the python console.

**Comment by lokeshwarlakhi** [comment]
Hello @vipgupta I can do this. can you assign this to me.

**Comment by vipgupta** [comment]
Done!
